import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowUp, Copy, Download, Play, Plus, Redo2, Save, Share2, Trash2, Undo2, Upload } from 'lucide-react';
import { CONFIG_VERSION, FAMILIES } from '../engine/catalog';
import { adaptRecipeCopy, formatDuration, inspectRecipe, newRecipe, parseRecipe, PHASES, planRecipe, recipeLink, RECIPE_LIMITS, spaceRecipe, starterRecipe, STARTER_NAMES } from '../experience/ShowRecipe';
import type { ShowCue, ShowRecipe } from '../experience/ShowRecipe';
import { browserStore, downloadBlob, exportRecipe, LIBRARY_KEY, readNights, writeNights } from '../experience/NightLibrary';
import type { SavedNight } from '../experience/NightLibrary';
type Props={initialRecipe?:ShowRecipe|null;onDraftChange?:(recipe:ShowRecipe)=>void;onPlay:(recipe:ShowRecipe)=>string|void;onStop:()=>void;playing:boolean;onWatch:()=>void};
/** The studio is loaded only on demand. Draft history and storage are bounded, never frame-driven. */
export default function NightStudio({initialRecipe,onDraftChange,onPlay,onStop,playing,onWatch}:Props){
  const [draft,setDraft]=useState(()=>initialRecipe?parseRecipe(initialRecipe):newRecipe());
  const [past,setPast]=useState<ShowRecipe[]>([]),[future,setFuture]=useState<ShowRecipe[]>([]);
  const [tab,setTab]=useState<'create'|'saved'>('create');
  const [library,setLibrary]=useState(()=>readNights(browserStore()));
  const [message,setMessage]=useState(initialRecipe?'Recipe loaded for review. Nothing will play or save until you choose.':'');
  const [link,setLink]=useState('');
  const [renaming,setRenaming]=useState<string|null>(null),[rename,setRename]=useState('');
  const [deleteId,setDeleteId]=useState<string|null>(null);
  const file=useRef<HTMLInputElement>(null);
  const mounted=useRef(true);
  const importGeneration=useRef(0);
  useEffect(()=>{onDraftChange?.(draft);},[draft,onDraftChange]);
  useEffect(()=>{mounted.current=true;const sync=()=>setLibrary(readNights(browserStore()));window.addEventListener('storage',sync);return()=>{mounted.current=false;window.removeEventListener('storage',sync);};},[]);
  const update=(recipe:ShowRecipe)=>{setPast(p=>[...p.slice(-(RECIPE_LIMITS.history-1)),draft]);setFuture([]);setDraft(recipe);setLink('');};
  const editCue=(index:number,value:Partial<ShowCue>)=>update({...draft,cues:draft.cues.map((c,i)=>i===index?{...c,...value}:c)});
  const plan=planRecipe(draft);
  const mutate=(change:(nights:SavedNight[])=>SavedNight[])=>{
    try{const current=readNights(browserStore());if(current.warning)throw new Error(current.warning);const nights=change(current.nights);writeNights(browserStore(),nights);setLibrary({nights,warning:''});return true;}catch(error){setMessage((error as Error).message);return false;}
  };
  const save=(recipe:ShowRecipe)=>{try{const clean=parseRecipe(recipe);if(mutate(nights=>[...nights,{id:crypto.randomUUID(),recipe:clean}]))setMessage('Saved on this browser only. Export a recipe file for a portable backup.');}catch(error){setMessage((error as Error).message);}};
  const share=async(recipe:ShowRecipe)=>{
    try{const url=recipeLink(recipe,location.href);setLink(url);
      if(navigator.share){try{await navigator.share({title:recipe.name,url});if(mounted.current)setMessage('Share action completed.');}catch(error){if(mounted.current)setMessage(error instanceof DOMException&&error.name==='AbortError'?'Sharing cancelled. The link is still available below.':'Native sharing was unavailable. Copy the link or export the recipe.');}}
      else setMessage('Copy the link below, or export the recipe. Anyone receiving it can read and play the show.');
    }catch(error){setMessage((error as Error).message);}
  };
  const move=(i:number,delta:number)=>{const next=i+delta;if(next<0||next>=draft.cues.length||draft.cues[next].phase!==draft.cues[i].phase)return;const cues=[...draft.cues];[cues[i],cues[next]]=[cues[next],cues[i]];update({...draft,cues});};
  const loadFile=async(input:File|undefined)=>{if(!input)return;const generation=++importGeneration.current;try{if(input.size>RECIPE_LIMITS.bytes)throw new Error('This file exceeds the 12 KB recipe limit.');const recipe=parseRecipe(await input.text());if(mounted.current&&generation===importGeneration.current){update(recipe);setTab('create');setMessage('Imported for review. Your sound and comfort settings are unchanged.');}}catch(error){if(mounted.current)setMessage((error as Error).message);}finally{if(file.current)file.current.value='';}};
  return <div className='night-studio'>
    <div className='studio-tabs' role='group' aria-label='Night studio views'><button type='button' aria-pressed={tab==='create'} onClick={()=>setTab('create')}>Create a show</button><button type='button' aria-pressed={tab==='saved'} onClick={()=>setTab('saved')}>Saved nights <span>{library.nights.length}</span></button></div>
    <p className='panel-note'>A personal opening, build-up and finale. No account, uploads or public gallery.</p>
    {message&&<p className='studio-status' role='status'>{message}</p>}
    {playing&&<div className='studio-playing'><span>Your show is paused while this panel is open.</span><button type='button' className='secondary-button' onClick={onWatch}>Back to the show</button><button type='button' className='text-button' onClick={onStop}>Stop future cues</button></div>}
    {tab==='create'?<>
      <label className='studio-field'>Show name<input maxLength={60} value={draft.name} onChange={e=>update({...draft,name:e.target.value})}/></label>
      <div className='studio-starters'><span>Start with</span>{STARTER_NAMES.map((name,i)=><button className='text-button' type='button' key={name} onClick={()=>update(starterRecipe(i,draft.seed))}>{name}</button>)}</div>
      <div className='studio-tools'><button type='button' className='studio-icon' aria-label='Undo edit' disabled={!past.length} onClick={()=>{const previous=past[past.length-1];setPast(p=>p.slice(0,-1));setFuture(f=>[draft,...f].slice(0,RECIPE_LIMITS.history));setDraft(previous);}}><Undo2 size={17}/></button><button type='button' className='studio-icon' aria-label='Redo edit' disabled={!future.length} onClick={()=>{setPast(p=>[...p,draft].slice(-RECIPE_LIMITS.history));setDraft(future[0]);setFuture(f=>f.slice(1));}}><Redo2 size={17}/></button><span>{draft.kind==='finale'?'Finite preset':`${draft.cues.length} / 12 cues`} · approximately {formatDuration(plan.seconds)} including falling effects</span></div>
      {draft.kind==='finale'?<p className='studio-empty'>This is the current 32-second Finale preset, followed by its remaining sparks. The held musical scores are not included.</p>:PHASES.map(phase=><section key={phase} className='composer-phase' aria-label={phase}>
        <h3>{phase}</h3>
        {draft.cues.map((cue,i)=>cue.phase===phase?<div className='composer-cue' key={`${phase}-${i}`} data-cue-index={i}>
          <div className='cue-heading'><span>Cue {i+1} · {formatDuration(plan.cues[i].at)}</span><div><button className='studio-icon' type='button' aria-label={`Move cue ${i+1} up`} disabled={i===0||draft.cues[i-1].phase!==phase} onClick={()=>move(i,-1)}><ArrowUp size={15}/></button><button className='studio-icon' type='button' aria-label={`Move cue ${i+1} down`} disabled={i===draft.cues.length-1||draft.cues[i+1].phase!==phase} onClick={()=>move(i,1)}><ArrowDown size={15}/></button><button className='studio-icon' type='button' aria-label={`Duplicate cue ${i+1}`} disabled={draft.cues.length>=12} onClick={()=>update({...draft,cues:[...draft.cues.slice(0,i+1),{...cue,gap:12},...draft.cues.slice(i+1)]})}><Copy size={15}/></button><button className='studio-icon' type='button' aria-label={`Remove cue ${i+1}`} disabled={draft.cues.length===1} onClick={()=>update({...draft,cues:draft.cues.filter((_,n)=>n!==i)})}><Trash2 size={15}/></button></div></div>
          <label className='studio-field'>Firework<select aria-label={`Cue ${i+1} firework`} value={cue.family} onChange={e=>editCue(i,{family:e.target.value as ShowCue['family']})}>{FAMILIES.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>
          <div className='cue-fields'><label className='studio-field'>Position<select aria-label={`Cue ${i+1} position`} value={cue.position} onChange={e=>editCue(i,{position:Number(e.target.value)})}>{[.2,.35,.5,.65,.8].map((v,n)=><option value={v} key={v}>{['Left','Left centre','Centre','Right centre','Right'][n]}</option>)}{![.2,.35,.5,.65,.8].includes(cue.position)&&<option value={cue.position}>Custom {Math.round(cue.position*100)}%</option>}</select></label><label className='studio-field'>Gap before (seconds)<input aria-label={`Cue ${i+1} gap`} type='number' min={0} max={30} step={1} value={cue.gap} onChange={e=>editCue(i,{gap:Math.max(0,Math.min(30,Number(e.target.value)||0))})}/></label></div>
        </div>:null)}
        <button type='button' className='text-button' disabled={draft.cues.length>=12} onClick={()=>{const cues=[...draft.cues,{family:'multicolor-peony' as const,position:.5,gap:12,phase}].sort((a,b)=>PHASES.indexOf(a.phase)-PHASES.indexOf(b.phase));update({...draft,cues});}}><Plus size={15}/> Add {phase.toLowerCase()} cue</button>
      </section>)}
      {plan.conflicts.length>0&&<div className='studio-validation' role='alert'><strong>This arrangement needs more room.</strong>{plan.conflicts.map((issue,i)=><p key={i}>{issue}</p>)}<button type='button' className='secondary-button' onClick={()=>update(spaceRecipe(draft))}>Space cues safely</button></div>}
      <details className='panel-detail'><summary>Replay details</summary><label className='studio-field'>Variation seed<input aria-label='Variation seed' type='number' min={0} max={4294967295} value={draft.seed} onChange={e=>update({...draft,seed:Math.max(0,Math.min(4294967295,Math.floor(Number(e.target.value)||0)))})}/></label><p>Recipes preserve cue order and variation on this engine version. Device, quality and comfort settings adapt the appearance; pixels are not identical across devices.</p></details>
      <p className='fine-print'>Play from start deliberately clears the current sky. Editing alone never changes a committed rocket. A stricter viewport check runs before launch.</p>
      <div className='studio-actions'><button type='button' className='primary-button' disabled={Boolean(plan.conflicts.length)||!draft.name.trim()} onClick={()=>{try{const error=onPlay(parseRecipe(draft));if(error)setMessage(error);}catch(error){setMessage((error as Error).message);}}}><Play size={16}/>Play from start</button><button type='button' className='secondary-button' onClick={()=>save(draft)}><Save size={16}/>Save night</button><button type='button' className='secondary-button' onClick={()=>{try{exportRecipe(draft);}catch(error){setMessage((error as Error).message);}}}><Download size={16}/>Export recipe</button><button type='button' className='secondary-button' onClick={()=>void share(draft)}><Share2 size={16}/>Share recipe</button></div>
    </>:<>
      {library.warning&&<div role='alert' className='studio-validation'><p>{library.warning}</p><p>Stored bytes have not been overwritten. Export the raw backup before resetting.</p><button type='button' className='secondary-button' onClick={()=>{try{downloadBlob(new Blob([browserStore().getItem(LIBRARY_KEY)||'[]'],{type:'application/json'}),'firecrackers-library-backup.json');}catch{setMessage('Local storage is not readable.');}}}>Export raw backup</button></div>}
      {!library.nights.length&&!library.warning&&<p className='studio-empty'>No saved nights yet. Create a show and choose Save night, or import a recipe below.</p>}
      {library.nights.map(n=><article className='saved-night' key={n.id}><h3>{n.recipe.name}</h3><p>{n.recipe.kind==='finale'?'Finale preset':`${n.recipe.cues.length} cues`}{n.recipe.engine===CONFIG_VERSION?` · approximately ${formatDuration(planRecipe(n.recipe).seconds)}`:''}</p>{n.recipe.engine!==CONFIG_VERSION&&<p className='recipe-version-note'>Saved with {n.recipe.engine}. The original is preserved. Adapt a separate copy to preview it on this version; timing and appearance may differ.</p>}<div className='studio-actions'><button className='primary-button' type='button' aria-label={`${n.recipe.engine===CONFIG_VERSION?'Review':'Adapt a copy of'} ${n.recipe.name}`} onClick={()=>{const current=n.recipe.engine===CONFIG_VERSION;update(current?n.recipe:adaptRecipeCopy(n.recipe));setTab('create');setMessage(current?'Review, rename or play this saved recipe. Saving again makes a separate copy.':'Adapted a separate draft for this version. Your original is unchanged; review the new timing before playing or saving.');}}>{n.recipe.engine===CONFIG_VERSION?'Review / edit':'Adapt a copy'}</button><button className='text-button' type='button' aria-label={`Rename ${n.recipe.name}`} onClick={()=>{setRenaming(n.id);setRename(n.recipe.name);}}>Rename</button><button className='secondary-button' type='button' aria-label={`Export ${n.recipe.name}`} onClick={()=>exportRecipe(n.recipe)}><Download size={16}/></button><button className='secondary-button' type='button' disabled={n.recipe.engine!==CONFIG_VERSION} aria-label={`Share ${n.recipe.name}`} onClick={()=>void share(n.recipe)}><Share2 size={16}/></button><button className='secondary-button' type='button' disabled={n.recipe.engine!==CONFIG_VERSION} aria-label={`Duplicate ${n.recipe.name}`} onClick={()=>save({...n.recipe,name:`${n.recipe.name.slice(0,54)} copy`})}><Copy size={16}/></button><button className='text-button' type='button' aria-label={`Delete ${n.recipe.name}`} onClick={()=>setDeleteId(n.id)}><Trash2 size={16}/></button></div></article>)}
      {renaming&&<div className='studio-validation'><label className='studio-field'>New show name<input maxLength={60} value={rename} onChange={e=>setRename(e.target.value)}/></label><button className='secondary-button' type='button' onClick={()=>{if(mutate(items=>items.map(n=>n.id===renaming?{...n,recipe:inspectRecipe({...n.recipe,name:rename})}:n))){setRenaming(null);setMessage('Saved night renamed.');}}}>Save name</button><button className='text-button' type='button' onClick={()=>setRenaming(null)}>Cancel rename</button></div>}
      <p className='fine-print'>Saved only in this browser. Private browsing or clearing site data may remove nights. Keep exported copies.</p>
      {(library.nights.length>0||library.warning)&&<button type='button' className='text-button' onClick={()=>setDeleteId('all')}>Delete all saved nights</button>}
      {deleteId&&<div className='studio-validation'><p>{deleteId==='all'?'Delete every locally saved night? This cannot be undone.':'Delete this saved night? This cannot be undone.'}</p><button type='button' className='secondary-button' onClick={()=>{try{if(deleteId==='all'){browserStore().removeItem(LIBRARY_KEY);setLibrary({nights:[],warning:''});setMessage('Local saved nights deleted. Preferences and favourites are unchanged.');}else mutate(items=>items.filter(n=>n.id!==deleteId));}catch{setMessage('This browser could not delete the local library.');}setDeleteId(null);}}>Confirm deletion</button><button className='text-button' type='button' onClick={()=>setDeleteId(null)}>Cancel</button></div>}
    </>}
    <div className='studio-import'><input hidden ref={file} type='file' accept='.json,application/json' aria-label='Import show recipe file' onChange={e=>void loadFile(e.target.files?.[0])}/><button type='button' className='text-button' onClick={()=>file.current?.click()}><Upload size={16}/>Import recipe file</button></div>
    {link&&<div className='studio-link'><label className='studio-field'>Share link<textarea readOnly value={link} rows={2}/></label><p className='fine-print'>Anyone with this link can read the recipe. It does not enable sound or launch automatically.</p><button type='button' className='secondary-button' onClick={()=>{if(!navigator.clipboard){setMessage('Clipboard is unavailable. Select and copy the link.');return;}void navigator.clipboard.writeText(link).then(()=>setMessage('Link copied.'),()=>setMessage('Clipboard permission was unavailable. Select and copy the link.'));}}>Copy link</button></div>}
  </div>;
}
